meta:
  app_id: simple_zodiac_data
  display_name: Simple Zodiac Data
  version: 1.0.0-dev.4
  vendor: verndale
  summary: Adds a Zodiac Sign attribute to customers. For customers who have birthdates, calculates and sets the customers' Zodiac Sign.
  support_url: https://www.verndale.com
  contact_email: doug.yoder@verndale.com
  categories:
    - Data Quality & Enrichment
  availability:
    - us

runtime: node18

functions:
  trigger_zodiac_job:
    entry_point: TriggerZodiacJob
    description: Starts the CalculateZodiacs job

jobs:
  calculate_zodiacs:
    entry_point: CalculateZodiacs
    # runs every hour
    # cron: 0 0 * * * ?
    description: Performs an hourly calculation of Zodiac signs

